server:
  port: 8766
## netty服务器端口
netty:
  udp:
    port: 6688
  so:
    rcvbuf: 268435456
    sndbuf: 65536

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          min-partition-count: 1      #主题分区个数，集群部署时请根据需求修改，分区数 >= download service 集群数量
      bindings:
        download-message-out:
          destination: downloadMessages
          contentType: application/json
          producer:
            compressionType: gzip
logging:
  level: error
